import RPi.GPIO as GPIO

HEAD_DIR = 3
HEAD_STEP = 5
HEAD_SLEEP = 7
HEAD_HOME = 37

HEAD_V = 200
HEAD_sV = 1000
HEAD_Ramp = 1
HEAD_SLACK = 2

VALVE_DIR = 11
VALVE_STEP = 13
VALVE_SLEEP = 15
VALVE_HOME = 35

VALVE_V = 200
VALVE_sV = 1000
VALVE_Ramp = 1
VALVE_SLACK = 2

GEARRATIO = 100.51
MICROSTEPS = 16.0
ADJUSTMENT = 200.0 / 360.0 * MICROSTEPS
STEP_PER_ANGLE = 1 * GEARRATIO * ADJUSTMENT

KEEP_DIR = False
RESET_DIR = True
CHECK_DIR = True
NOT_CHECK_DIR = False
MATCH = GPIO.HIGH
NOT_MATCH = GPIO.LOW

CLOCKWISE = 0
COUNTERCLOCKWISE = 1
OPEN_DIR = COUNTERCLOCKWISE
CLOSE_DIR = CLOCKWISE
HEAD_POS_COUNT = 4
VALVE_POS_COUNT = 20

RUNNING = True
IDLE = False

VALVE_CHECK_FREQ = 0.01
